version: "3.9"

services:
  db:
    image: postgres:15
    container_name: registro_visitantes-db-v2
    restart: always
    environment:
      POSTGRES_DB: visitantesdb
      POSTGRES_USER: gerson
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - visitantes-net

  backend:
    build:
      context: ./backend
    container_name: registro_visitantes-backend-v2
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/visitantesdb
      SPRING_DATASOURCE_USERNAME: gerson
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      APP_VERSION: "2.0"
      ADMIN_SECRET: "grupo21"   # senha administrativa para criar usuários
    depends_on:
      - db
    networks:
      - visitantes-net

  frontend:
    build:
      context: ./frontend
    container_name: registro_visitantes-frontend-v2
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - visitantes-net

volumes:
  postgres_data:

networks:
  visitantes-net:
    driver: bridge

