-- Cria a tabela para armazenar os dados dos moradores
CREATE TABLE IF NOT EXISTS moradores (
    id SERIAL PRIMARY KEY,
    casa INTEGER NOT NULL,
    nome_morador VARCHAR(100) NOT NULL
);

-- Insere os dados de cada casa na tabela moradores
INSERT INTO moradores (casa, nome_morador) VALUES
(1, 'Antonio'),
(1, 'Aparecida'),
(2, 'Carlos'),
(2, 'Viviane'),
(2, 'Milena'),
(2, 'Helena'),
(2, 'Isadora'),
(3, 'Gerson'),
(3, 'Luciana'),
(3, 'Beatriz'),
(3, 'Gabrielle'),
(4, 'Joao'),
(4, 'Tamisa'),
(4, 'Joao Jr.'),
(4, 'Victor'),
(4, 'Carol'),
(5, 'Arthur'),
(5, 'Eliene'),
(6, 'Orlando'),
(6, 'Joana'),
(6, 'Carlos'),
(6, 'Marcela'),
(7, 'Leonardo'),
(7, 'Vania'),
(8, 'Jesse'),
(8, 'Maria'),
(8, 'Leonardo'),
(9, 'Maurici'),
(9, 'Noemia'),
(9, 'Claudia'),
(10, 'Manoel'),
(10, 'Antonia'),
(11, 'Terezinha'),
(11, 'Silvana'),
(11, 'Luana'),
(11, 'Maria'),
(12, 'Alvin'),
(12, 'Claudete'),
(12, 'Joana'),
(13, 'Osmar'),
(13, 'Rodrigo'),
(13, 'Joao'),
(14, 'Jose Carlo'),
(14, 'Marilia'),
(14, 'Mariano'),
(15, 'Leticia'),
(15, 'Roberto'),
(16, 'Leonardo'),
(16, 'Valquiria'),
(17, 'Raimunda'),
(17, 'Andre'),
(17, 'Valeria'),
(18, 'Vania'),
(18, 'Alice'),
(18, 'Aliciana'),
(18, 'Artur'),
(19, 'Rosangela'),
(19, 'Ricardo'),
(19, 'Marcelo'),
(20, 'Fabio'),
(20, 'Josie');